"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['sudoku.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
		'iconfile': '1024px-Sudoku_dot_notation', 
		'plist': {'CFBundleShortVersionString':'0.0.2'},
		'resources':['problems']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
